#!/bin/bash

VER="1.15.0"
REL="06fdc8"

[ -d $HOME/Kasm ] || mkdir -p $HOME/Kasm
cd $HOME/Kasm
curl -O https://kasm-static-content.s3.amazonaws.com/kasm_release_${VER}.${REL}.tar.gz
tar -xf kasm_release_${VER}.${REL}.tar.gz
sudo bash kasm_release/install.sh --accept-eula --swap-size 8192
rm -f kasm_release_${VER}*.tar.gz
